version: "2"
services:
  www:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:8.0.3-apache
    hostname: chat
    ports:
      - 8001:80
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
    links:
      - db:db
      - nginx:nginx
      - websocket:websocket
    networks:
      - default
  db:
    image: mysql
    hostname: chat_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: chat_pma
    links:
      - db:db
    ports:
      - 8000:8000
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - default
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx:alpine
    hostname: chat_nginx
    container_name: webservers
    links:
      - websocket:websocket
    ports:
      - 443:443
    networks:
        - default
  redis-chat:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    image: redis
    container_name: chat_redis
    volumes:
      - ./docker/redis/data:/data
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  websocket:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: node
    restart: always
    hostname: chat_node
    links:
      - redis-chat:redis-chat
    volumes:
      - ./www:/var/www/html
    ports:
      - 6001:6001
    networks:
      - default
volumes:
  persistent: